---

name: whichYamlParses
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Mark Greenaway <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  path: ^1.6.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  glob: ^1.1.7
  yaml: ^2.1.15
  path: ^1.6.2
